### ISSUE TITLE
Timeouts are not removed after they have completed

### ISSUE THREAD

**Issue by shawmanz32na** [bargoldi/time-events-manager#3]
This may be as-designed, but doesn't meet my expectations. I had expected that after a timeout had expired and executed its function, the timeout would be removed from the timeoutCollection. It appears that this is not the case, and than any timeouts that get scheduled remain in the timeoutCollection until manually cleared.

Instead, the timeouts should be removed from the time-events-manager once they're complete. Alternatively, another `getAllScheduled` method to get all those timeouts that have not expired/completed could get me what I want.

Here's a sample (QUnit) test case that shows the expected behavior and the failure.

    assert.equal(timeoutCollection.getAll().length, 0, "There should be no scheduled timeouts.");
    setTimeout(function() {doSomething();}, 1000);
    assert.equal(timeoutCollection.getAll().length, 1, "The scheduled timeout should be listed");
    waitFor(1500).then(function() {
        assert.equal(timoutCollection.getAll().length, 0, "The scheduled timeout has completed and should no longer be listed"); // This fails because the completed timeout is still in the list
    });

**Comment by zivpolack** [comment]
Original design was meant to help invesigating both scheduled and expired timeouts (hence providing the timestamp and handler of the timeouts).

We do agree `getAllScheduled` functionality may be useful and has it's place and it will be added.

**Comment by shawmanz32na** [comment]
I made some edits and had to squash commits. It looks like GitHub is a bit overzealous when it comes to tracking the referenced commits. Sorry for the noise.

**Comment by shawmanz32na** [comment]
#4 has been accepted. Closing.
